server:
  port: 8082

api:
  coingecko:
    key: CG-s43w3741nsRt1x5T69gEA6S9
    domain: api.coingecko.com
    path: /api/v3
    endpoint: /coins/markets
    coins:
      vs_currency: usd
      order: market_cap_desc
      per_page: 100
      page: 1
      sparkline: false
      locale: en
    coin-ids: btc,eth

# https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&x_cg_demo_api_key=CG-s43w3741nsRt1x5T69gEA6S9

redis-key:
  crypto:
    coingecko:
      coins-markets:
        currency: USD
        coin-ids: btc,eth

spring.data.redis:
  host: localhost
  password: 6379
  database: 2
  # Redis默认情况下有16个分片，这里配置具体使用的分片，默认是0
  lettuce:
    pool:
      # 当池耗尽时，在引发异常之前连接分配可以阻塞的最长时间（使用负值表示没有限制） 默认 -1
      max-wait: -1ms
      # 连接池最大连接数（使用负值表示没有限制） 默认 8
      max-active: 8
      # 连接池中的最大空闲连接 默认 8
      max-idle: 8
      # 连接池中的最小空闲连接 默认 0
      min-idle: 0
  # 连接超时时间
  timeout: 10000ms
  # 一般来说是不用配置的，Spring Cache 会根据依赖的包自行装配
  cache:
    type: redis
